# Generated by Django 4.2.3 on 2023-07-23 17:48
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('todo', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]